matrix:
  include:
    - language: java
      before_script:
        - cd java

    - language: ruby
      before_script:
        - cd ruby
      before_install: gem install bundler -v 2.0.1 && bundle install
      sudo: false
      cache: bundler
      rvm:
        - 2.5.3
